apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv-0
  labels:
    type: local
    app: spilo
    application: spilo
spec:
  storageClassName: pg-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv-1
  labels:
    type: local
    app: spilo
    application: spilo
spec:
  storageClassName: pg-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db1"
