apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 3 
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        volumeMounts:
        - name: pg-pv
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pg-pv
        persistentVolumeClaim:
          claimName: pg-pvc
